using UnityEngine;

// 적 우주선의 탄약발사를 처리하는 스크립트.
public class EnemyShoot : MonoBehaviour
{
    // 필드
    // 발사 간격
    [SerializeField] private float shootInterval = 1.5f;
    [SerializeField] private float bulletSpeed = 3f;
    [SerializeField] private GameObject bulletPrefab;

    // 플레이어의 트랜스폼을 참조하는 변수
    private Transform refPlayer;

    // 경과 시간을 계산하는 변수
    private float elapsedTime = 0f;

    private void Awake()
    {
        // 플레이어 게임 오브젝트를 검색한 뒤에 refPlayer에 트랜스폼 저장
        if (GameObject.FindGameObjectWithTag("Player") != null)
        {
            refPlayer = GameObject.FindGameObjectWithTag("Player").transform;
        }
    }

    private void Update()
    {
        elapsedTime += Time.deltaTime;

        if (elapsedTime > shootInterval)
        {
            Shoot();
            elapsedTime = 0f;
        }
    }

    // 발사 메소드.
    private void Shoot()
    {
        // 검증.
        if (refPlayer == null)
            return;

        // 플레이어의 위치를 향하는 방향 구하기.
        Vector3 direction = refPlayer.position - transform.position;

        // 프리팹을 이용해 탄약을 생성하고,
        var newBullet = Instantiate(bulletPrefab, transform.position, Quaternion.identity);

        // rigidbody2d 컴포넌트에 속도(빠르기/방향) 설정.
        float speed = Random.Range(bulletSpeed * 0.8f, bulletSpeed * 1.2f);
        newBullet.GetComponent<Rigidbody2D>().velocity = direction.normalized * speed;
    }
}
